//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavBilgileri
    {
        public int SinavID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public string SinavAdi { get; set; }
        public Nullable<decimal> SinavNotu { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
